application:
  title: WordCamp Europe 2018
  url: http://opencfp.local
  email: hello@wp-europe.org
  eventurl: https://2018.europe.wordcamp.org/
  event_location: Belgrade, Serbia
  enddate: 15 January 2018
  show_submission_count: false
  airport: BEG
  arrival: 2018-06-14
  departure: 2018-06-16
  secure_ssl: false
  online_conference: false
  date_format: j F Y
  date_timezone: "Europe/Belgrade"
  coc_link: https://2018.europe.wordcamp.org/code-of-conduct/

api:
  enabled: true

cache:
  enabled: false

database:
  host: 127.0.0.1
  database: cfp
  dsn: mysql:dbname=cfp;host=127.0.0.1
  user: root
  password: ~

log:
  level: error

mail:
  host: ~
  port: ~
  username: ~
  password: ~
  encryption: ~
  auth_mode: ~

talk:
  categories:
    development: Development
    design: Design
    community: Community
    content: Content
    business: Business
    other: Other
  levels:
    entry: Entry level
    mid: Mid-level
    advanced: Advanced
  types:
    lightning: Lightning talk (10 mins)
    long: Long talk (30 mins, 15mins Q&A)

security:
  firewalls:
    secured_area:
      form_forgot:
        csrf_parameter: _csrf_security_token
        csrf_token_id: forgot_password
